name: build-release
run-name: Release of ${{ github.repository }} by ${{ github.actor }}
on:
  push:
    branches:
      - prod
      - feature/workflow-gh-cli-release

permissions:
  contents: write

jobs:
  build-release-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: 'BUILD: Composer + NPM'
        run:
          npm install &&
          npm run build

      - name: 'PACKAGE: Artifact Name'
        run:
          repo=${{ github.repository }} &&
          repo=${repo#"hpuit/"} &&
          artifact="${repo}.tar.gz" &&
          echo "ARTIFACT=${artifact}" >> $GITHUB_ENV

      - name: 'PACKAGE: Release Number'
        run:
          version=$(<VERSION.md).${{ github.run_number }} &&
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: 'PACKAGE: Artifact File'
        run:
          tar
            --exclude='*.md'
            --exclude='.git*'
            --exclude='node_modules'
            --exclude='output.log'
            --exclude='package*'
            --exclude='webpack*'
            --exclude='src'
            -cf - * | gzip -c > "${{ env.ARTIFACT }}"

      - name: 'RELEASE: Create and Upload'
        id: create-release-and-upload
        run: |
          gh release create "${{ env.VERSION }}" "./${{ env.ARTIFACT }}" \
            --title "${{ env.VERSION }}" \
            --notes-from-tag \
            --repo "${{ github.repository }}" \
            --draft=true \
            --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
